server:
  port: 8618

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  使用默认数据源HikariCP
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.174.128:3306/pm?useUnicode=true&characterEncoding=utf8&useSSL=false


logging:
  config: classpath:log4j2.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #开启的驼峰效果: 实体类中的字段 userName 自动映射对应数据库中的 user_name