server:
  port: 8618

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  使用默认数据源HikariCP
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.24.2:3306/pm?useUnicode=true&characterEncoding=utf8&useSSL=false
  # 邮件服务配置
  mail:
    host: smtp.zlgmcu.com
    port: 465
    username: noreply_developer@zlg.cn
    password: eRXP528E
    protocol: smtps
    properties:
      mail:
        smtp:
          from: noreply_developer@zlg.cn
          auth: true
#        debug: true



logging:
  config: classpath:log4j2.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #开启的驼峰效果: 实体类中的字段 userName 自动映射对应数据库中的 user_name